'use strict';

const fs = require('fs');
const path = require('path');
const {spawn} = require('child_process');

/**
 * The app side of the themed updater (`hmo-updater.exe`).
 *
 * `MainWindow.installUpdate()` has three tiers and this module is the first
 * one. Everything here is written so that **failing is cheap**: the app does
 * not quit until the helper has written its ready-file, so a missing folder, a
 * quarantined exe, a spawn error or a slow start all end the same way — a log
 * line and the stock low-priority installer, with the user still on a working
 * app. See docs/SPEC-UPDATER.md §5.
 *
 * No electron import, on purpose: everything that needs `app.getPath`,
 * `screen` or a BrowserWindow is decided by the caller and passed in, which is
 * what lets the tests drive this against `mkdtemp` and a fake clock. Same tier
 * as `diagnostics/report.js` (see `docs/agents/architecture.md`, "Pure vs impure").
 */

/** What the shipped folder is called under `resources/`. */
const HELPER_DIR_NAME = 'updater';
const HELPER_EXE = 'hmo-updater.exe';

/**
 * Prefix of the working copy's folder. The stale cleanup keys on it, so it is
 * one constant — and it has to be distinctive, because the folder now lives
 * *inside* electron-updater's cache directory next to `pending/` and
 * `installer.exe`, none of which are ours to delete.
 */
const HELPER_PREFIX = 'helper-';

/**
 * How long the app waits for the helper to say it is on screen.
 *
 * Four seconds is generous for "start a 90 KB WPF process and show a window"
 * and short enough that a user who is watching does not notice the difference
 * between this and the stock path. It is also the whole antivirus story: a
 * blocked exe never writes the file, the wait expires, and the update happens
 * the old way.
 */
const READY_TIMEOUT_MS = 4000;
const READY_POLL_MS = 100;

/**
 * `<ready-file>.abort` — written by the app when it gives up on the helper.
 * `updater/Runner.cs` (`AbortSuffix`) carries the same literal.
 */
const ABORT_SUFFIX = '.abort';

/** Stale helper copies are swept on the next start. */
const STALE_MS = 60 * 60 * 1000;

/** The helper clamps to this too; both sides agree with docs/SPEC-UPDATER.md §1. */
const MIN_WIDTH = 560;
const MIN_HEIGHT = 380;

/** Where electron-builder puts the folder from `build.extraResources`. */
function helperSourceDir(resourcesPath) {
    return path.join(resourcesPath, HELPER_DIR_NAME);
}

/**
 * `helper-0.5.1-a3f19c`.
 *
 * The version is in the name so a log or a stray folder says which update left
 * it behind, and the random tail keeps two attempts (or two users on one
 * machine) from sharing a directory that one of them is about to delete.
 *
 * @param {string} version
 * @param {string} [random] injected by the tests
 */
function helperFolderName(version, random) {
    const clean = String(version || '0.0.0').replace(/[^0-9A-Za-z._-]/g, '');
    const tail = random || Math.random().toString(16).slice(2, 8);
    return `${HELPER_PREFIX}${clean}-${tail}`;
}

/** electron-builder always writes this key into `resources/app-update.yml`. */
const CACHE_DIR_NAME_KEY = /^updaterCacheDirName:\s*(.+)$/m;

/**
 * `updaterCacheDirName` out of an `app-update.yml`, or null.
 *
 * Two lines of parsing instead of a YAML dependency: the file is generated by
 * electron-builder, the value is a plain folder name, and this is the only key
 * ever read from it.
 */
function updaterCacheDirName(yml) {
    if (typeof yml !== 'string') return null;
    const match = yml.match(CACHE_DIR_NAME_KEY);
    if (!match) return null;
    const value = match[1].trim().replace(/^['"]|['"]$/g, '');
    return value || null;
}

/**
 * Where the working copy of the helper lives: **electron-updater's own cache
 * directory**, `%LOCALAPPDATA%\<updaterCacheDirName>\`, the folder that already
 * holds `pending\<Setup>.exe`.
 *
 * Not `%TEMP%`, and that is not a preference. Bitdefender's Advanced Threat
 * Defense fired *"Malicious behavior blocked — blocked all applications
 * involved"* (SuspiciousBehavior.22E1418466DA1) on this machine when an
 * unsigned NSIS installer was started from a folder under `%TEMP%`: it killed
 * the whole launching process tree and neutralised the installer by
 * lower-casing its `MZ` signature to `mz` so it could never run again. Running
 * unsigned executables out of the user's temp directory is a textbook malware
 * shape, and a heuristic cannot tell us from it. The updater cache is where
 * electron-updater has *already* written and run the installer for every update
 * this app has ever shipped, so it is the one location on the machine with
 * evidence that this exact behaviour is tolerated.
 *
 * Derivation, in order of how much we trust it:
 *  1. `cacheDir` — what `autoUpdater.downloadedUpdateHelper.cacheDir` says. The
 *     library's own answer; nothing can be more correct than that.
 *  2. The installer's grandparent, because `downloadedFile` is always
 *     `<cacheDir>\pending\<name>.exe` (`DownloadedUpdateHelper`).
 *  3. `<localAppData>\<updaterCacheDirName from app-update.yml>`.
 *  4. `<localAppData>\<appName>-updater`, electron-updater's own last resort
 *     (`AppUpdater.getOrCreateDownloadHelper`: `dirName || this.app.name`).
 *
 * Pure, so all four branches are testable without an installed app.
 *
 * @returns {?string} null when nothing usable was supplied
 */
function helperHome(options = {}) {
    const {cacheDir, installerPath, localAppData, appName, cacheDirName} = options;
    if (cacheDir) return cacheDir;
    if (installerPath) {
        const parent = path.dirname(installerPath);
        if (path.basename(parent).toLowerCase() === 'pending') return path.dirname(parent);
    }
    if (localAppData && cacheDirName) return path.join(localAppData, cacheDirName);
    if (localAppData && appName) return path.join(localAppData, `${appName}-updater`);
    return null;
}

/**
 * Where the helper window goes.
 *
 * The app's own window, in physical pixels, so the helper opens on exactly the
 * picture the user was already looking at. When the window is hidden in the
 * tray there is nothing to cover, so it is centred on the primary display at
 * the minimum size instead.
 *
 * Pure: the caller does the `screen.dipToScreenRect` conversion.
 *
 * @param {?{x: number, y: number, width: number, height: number}} windowRect
 * @param {{x: number, y: number, width: number, height: number}} primaryWorkArea
 * @param {number} [scaleFactor] the display's scale (1.5 at 150 %). Everything
 *   here is physical pixels, but the helper *lays out* in DIPs: at 150 % a
 *   560x380 px window is 373x253 DIPs and the error state does not fit in it.
 *   The minimum is therefore 560x380 **DIPs**, scaled up to pixels here.
 * @returns {{x: number, y: number, width: number, height: number}}
 */
function helperBounds(windowRect, primaryWorkArea, scaleFactor) {
    const area = primaryWorkArea || {x: 0, y: 0, width: 1920, height: 1080};
    const scale = Number(scaleFactor) >= 1 ? Math.min(4, Number(scaleFactor)) : 1;
    const minWidth = Math.round(MIN_WIDTH * scale);
    const minHeight = Math.round(MIN_HEIGHT * scale);
    if (!windowRect || !windowRect.width || !windowRect.height) {
        return {
            x: Math.round(area.x + (area.width - minWidth) / 2),
            y: Math.round(area.y + (area.height - minHeight) / 2),
            width: minWidth,
            height: minHeight
        };
    }
    return {
        x: Math.round(windowRect.x),
        y: Math.round(windowRect.y),
        width: Math.max(minWidth, Math.round(windowRect.width)),
        height: Math.max(minHeight, Math.round(windowRect.height))
    };
}

/**
 * The command line, in the order `updater/Options.cs` documents.
 *
 * Kept pure and tested because the two sides have to agree exactly and there is
 * no compiler to tell us they do not — a renamed switch would show up as a
 * helper that exits 2 and an update that quietly took the stock path.
 *
 * @returns {string[]}
 */
function buildUpdaterArgs(options) {
    const {installerPath, installDir, appExe, version, lang, waitPid, bounds, logPath, readyFile} = options;
    const b = bounds || {};
    const args = [
        '--installer', String(installerPath),
        '--install-dir', String(installDir),
        '--app-exe', String(appExe),
        '--version', String(version),
        '--lang', lang === 'it' ? 'it' : 'en',
        '--wait-pid', String(waitPid),
        '--bounds', [b.x, b.y, b.width, b.height].map(n => Math.round(Number(n) || 0)).join(','),
        '--log', String(logPath),
        '--ready-file', String(readyFile)
    ];
    // Only when the app window was not the focused window: the player may be
    // in a fullscreen match, and stealing focus there is worse than a plain
    // installer would have been.
    if (options.activate === false) args.push('--no-activate');
    return args;
}

/**
 * Copy the shipped helper somewhere it can survive its own update.
 *
 * It cannot run from `resources/updater`: NSIS uninstalls the old version
 * first, so the exe would be deleted out from under the running process (and on
 * Windows the *folder* cannot be removed while it is a process's image path,
 * which would make the uninstall fail as well).
 *
 * Shallow by design — the shipped folder is `hmo-updater.exe`, `icon.png` and
 * `fonts/`. A directory tree walk would be inventing a requirement.
 */
function copyHelper(from, to, fsImpl = fs) {
    fsImpl.mkdirSync(to, {recursive: true});
    for (const entry of fsImpl.readdirSync(from, {withFileTypes: true})) {
        const source = path.join(from, entry.name);
        const target = path.join(to, entry.name);
        if (entry.isDirectory()) copyHelper(source, target, fsImpl);
        else fsImpl.copyFileSync(source, target);
    }
}

/**
 * Wait for the helper's ready-file — the handshake the whole safety story
 * rests on.
 *
 * `fsImpl`, `now` and `sleep` are injected so a test can prove the timeout
 * without spending four seconds on it.
 *
 * @returns {Promise<boolean>} true when the file appeared in time
 */
async function waitForReadyFile(options) {
    const {
        file,
        timeoutMs = READY_TIMEOUT_MS,
        pollMs = READY_POLL_MS,
        fsImpl = fs,
        now = Date.now,
        sleep = (ms) => new Promise(resolve => setTimeout(resolve, ms)),
        isDead = () => false
    } = options;
    const deadline = now() + timeoutMs;
    for (;;) {
        try {
            if (fsImpl.existsSync(file)) return true;
        } catch (err) {
            // An unreadable temp directory is a "no" like any other.
            return false;
        }
        // A helper that already exited is never going to write the file; there
        // is no point spending the rest of the budget on it.
        if (isDead()) return false;
        if (now() >= deadline) return false;
        await sleep(pollMs);
    }
}

/**
 * `helper-*` folders older than an hour. Pure; the caller does the fs.
 *
 * The prefix filter is a safety rule, not an optimisation: this list is used to
 * delete directories inside electron-updater's cache, which also holds
 * `pending/`, `installer.exe` and the block maps. Nothing without our prefix is
 * ever returned.
 */
function staleHelperFolders(entries, now, maxAgeMs = STALE_MS) {
    return entries
        .filter(entry => entry && typeof entry.name === 'string' && entry.name.startsWith(HELPER_PREFIX))
        .filter(entry => (now - Number(entry.mtimeMs || 0)) > maxAgeMs)
        .map(entry => entry.name);
}

/**
 * Best-effort sweep of leftover helper copies.
 *
 * They are only left behind when the helper was killed or the machine lost
 * power mid-update, so this is housekeeping, not a guarantee. It never throws:
 * it runs on the startup path, where a thrown error would be an app that does
 * not start.
 *
 * @returns {number} how many folders were removed
 */
function cleanStaleHelpers(options = {}) {
    const {homeDir, now = Date.now(), maxAgeMs = STALE_MS, fsImpl = fs} = options;
    let removed = 0;
    if (!homeDir) return 0;
    try {
        const entries = fsImpl.readdirSync(homeDir, {withFileTypes: true})
            .filter(entry => entry.isDirectory())
            .map(entry => {
                let mtimeMs = 0;
                try {
                    mtimeMs = fsImpl.statSync(path.join(homeDir, entry.name)).mtimeMs;
                } catch (err) {
                    // Gone between readdir and stat: treat as ancient, the
                    // removal below will no-op.
                    mtimeMs = 0;
                }
                return {name: entry.name, mtimeMs};
            });
        for (const name of staleHelperFolders(entries, now, maxAgeMs)) {
            try {
                fsImpl.rmSync(path.join(homeDir, name), {recursive: true, force: true});
                removed++;
            } catch (err) {
                // Still running, or locked by a scanner. It will be tried again
                // on the next start.
            }
        }
    } catch (err) {
        // No cache directory yet (nothing has ever been downloaded) is the
        // normal case, not a problem to solve.
    }
    return removed;
}

/**
 * Copy the helper out of `resources/`, start it, and wait for it to say it is
 * on screen.
 *
 * **The caller must not quit until this resolves with `ok: true`.** That is the
 * entire contract: no ready-file, no quit (spec §5.2).
 *
 * @returns {Promise<{ok: boolean, reason: ?string, dir: ?string, exe: ?string,
 *                    args: ?string[], pid: ?number, readyFile: ?string}>}
 */
async function launchUpdater(options) {
    const {
        resourcesPath,
        version,
        readyTimeoutMs = READY_TIMEOUT_MS,
        fsImpl = fs,
        spawnFn = spawn,
        random
    } = options;

    const result = {ok: false, reason: null, dir: null, exe: null, args: null, pid: null, readyFile: null};

    const home = options.homeDir || helperHome(options);
    if (!home) {
        result.reason = 'no-helper-home';
        return result;
    }

    const source = helperSourceDir(resourcesPath);
    const sourceExe = path.join(source, HELPER_EXE);
    try {
        if (!fsImpl.existsSync(sourceExe)) {
            result.reason = 'helper-missing';
            return result;
        }
    } catch (err) {
        result.reason = 'helper-unreadable';
        return result;
    }

    const dir = path.join(home, helperFolderName(version, random));
    try {
        copyHelper(source, dir, fsImpl);
    } catch (err) {
        result.reason = `copy-failed: ${(err && err.message) || err}`;
        return result;
    }
    result.dir = dir;
    result.exe = path.join(dir, HELPER_EXE);
    result.readyFile = path.join(dir, 'ready');

    const args = buildUpdaterArgs(Object.assign({}, options, {readyFile: result.readyFile}));
    result.args = args;

    let child;
    let exited = false;
    try {
        child = spawnFn(result.exe, args, {
            // Detached with `unref`, because the app is about to quit and the
            // helper has to outlive it — it is the thing that watches this very
            // process go away (`--wait-pid`).
            detached: true,
            stdio: 'ignore',
            windowsHide: false,
            cwd: dir
        });
    } catch (err) {
        result.reason = `spawn-threw: ${(err && err.message) || err}`;
        return result;
    }
    if (!child) {
        result.reason = 'spawn-returned-nothing';
        return result;
    }
    // `spawn` reports a failed launch asynchronously and an unhandled 'error'
    // event is an uncaught exception — same trap as
    // `spawnInstallerAtLowPriority()`.
    let spawnError = null;
    if (typeof child.on === 'function') {
        child.on('error', (err) => {
            spawnError = (err && err.message) || String(err);
            exited = true;
        });
        child.on('exit', () => {
            exited = true;
        });
    }
    result.pid = child.pid || null;

    const ready = await waitForReadyFile(Object.assign({
        file: result.readyFile,
        timeoutMs: readyTimeoutMs,
        fsImpl,
        isDead: () => exited
    }, options.wait || {}));

    if (!ready) {
        result.reason = spawnError ? `spawn-failed: ${spawnError}` : (exited ? 'helper-exited' : 'no-ready-file');
        // Tell a helper that is merely *slow* (an antivirus still reading it)
        // that the app has moved on, BEFORE anything else happens: the caller
        // is about to start the stock installer and quit, and a helper that
        // came up late would see `--wait-pid` exit and start a second, silent
        // installer on top of it. The kill below is the first line of defence;
        // this file is the one that still holds when the kill does not
        // (`Runner.cs` checks for it right before starting the installer).
        try {
            fsImpl.writeFileSync(result.readyFile + ABORT_SUFFIX, 'abort');
        } catch (err) {
            // Best effort; the kill is still coming.
        }
        // Do not leave a window-less process behind holding the temp folder.
        try {
            if (!exited && typeof child.kill === 'function' && child.kill() === false) {
                result.reason += ' (kill failed)';
            }
        } catch (err) {
            // Already gone.
        }
        return result;
    }

    try {
        if (typeof child.unref === 'function') child.unref();
    } catch (err) {
        // Nothing to do; the app is quitting anyway.
    }
    result.ok = true;
    return result;
}

module.exports = {
    launchUpdater,
    buildUpdaterArgs,
    helperBounds,
    helperHome,
    updaterCacheDirName,
    helperSourceDir,
    helperFolderName,
    staleHelperFolders,
    cleanStaleHelpers,
    waitForReadyFile,
    copyHelper,
    HELPER_DIR_NAME,
    HELPER_EXE,
    HELPER_PREFIX,
    ABORT_SUFFIX,
    READY_TIMEOUT_MS,
    STALE_MS,
    MIN_WIDTH,
    MIN_HEIGHT
};
