#!/usr/bin/env node
'use strict';

/**
 * Dev only. `maps-src/markers.json` → `src/core/map-markers/markers.json`.
 *
 * The source file is the *authoring* format, written by the scripts in
 * `maps-src/marker-tools/`: it spells the Tab transform `{ax, bx, ay, by}` and
 * carries the provenance (`_about`, `iou`, `imageSize`). The shipped file is
 * the *runtime* format — the same one a map pack uses (`docs/SPEC-MAP-PACKS.md`
 * §2), so `shared/map-pack-rules.js` `validateMarkers` is the single validator
 * for both and `src/core/map-markers.js` has one shape to read.
 *
 * Two things change on the way across, and nothing else:
 *   1. `tab: {ax, bx, ay, by}` → `tab: {sx, tx, sy, ty}` (sx=ax, tx=bx, …).
 *      One spelling at runtime; the conversion happens here, once.
 *   2. `baked` is added: on the four bundled images the map's author drew the
 *      cellar / gate / car rings into the PNG itself, so the corner minimap
 *      must not draw them a second time. The in-game Tab map has none of them,
 *      which is why `baked` says *where* a layer already exists rather than
 *      removing it.
 *
 * Positions are copied verbatim — this script must never move a point.
 *
 *   node scripts/build-markers.js [--check]
 *
 * `--check` re-builds and compares against the committed file without writing,
 * which is what `npm test` uses to prove the two have not drifted.
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const SOURCE = path.join(ROOT, 'maps-src', 'markers.json');
const OUTPUT = path.join(ROOT, 'src', 'core', 'map-markers', 'markers.json');

/**
 * Layers the four bundled map images already draw themselves.
 *
 * Hand-written rather than derived, because it is a fact about the *pictures*
 * u/deftyconchgaming published, not about the data: the rings in the PNG are
 * exactly where `cellar`/`gate`/`car` were extracted from (Hough circles — see
 * the source file's `_about`). `gas` was traced from a separate spawn map and
 * is nowhere on the image, so it is the one layer the corner minimap adds.
 */
const BAKED_INTO_BUNDLED_IMAGES = ['cellar', 'gate', 'car'];

/** Round to the precision the source already carries, so no digit is invented. */
function round(value, digits) {
    const factor = Math.pow(10, digits);
    return Math.round(value * factor) / factor;
}

function build() {
    const source = JSON.parse(fs.readFileSync(SOURCE, 'utf-8'));
    const maps = {};
    for (const [key, entry] of Object.entries(source.maps || {})) {
        const out = {
            // Only the layers that exist: a map with no gas data must not gain
            // an empty layer, which would show an empty legend chip.
            layers: {},
            baked: BAKED_INTO_BUNDLED_IMAGES.filter(
                name => Object.prototype.hasOwnProperty.call(entry.layers || {}, name))
        };
        for (const [name, points] of Object.entries(entry.layers || {})) {
            out.layers[name] = points.map(p => ({x: p.x, y: p.y}));
        }
        if (entry.tab) {
            out.tab = {
                sx: round(entry.tab.ax, 6),
                tx: round(entry.tab.bx, 6),
                sy: round(entry.tab.ay, 6),
                ty: round(entry.tab.by, 6)
            };
        }
        maps[key] = out;
    }
    return {
        formatVersion: 1,
        _about: 'GENERATED by scripts/build-markers.js from maps-src/markers.json — do not edit by hand. '
            + 'Layer points are fractions (0-1) of the bundled map image. `baked` names the layers that '
            + 'image already draws itself (the corner minimap skips those; the in-game Tab map draws all '
            + 'of them). `tab` maps an image fraction onto the Tab map panel interior: u = sx*x + tx, '
            + 'v = sy*y + ty. All positions are POSSIBLE locations — the game activates a varying subset '
            + 'per match. Provenance: maps-src/markers.json `_about`.',
        credit: source.credit || null,
        maps
    };
}

function main() {
    const check = process.argv.includes('--check');
    const built = JSON.stringify(build(), null, 2) + '\n';
    if (check) {
        const current = fs.existsSync(OUTPUT) ? fs.readFileSync(OUTPUT, 'utf-8') : '';
        if (current !== built) {
            console.error(`${path.relative(ROOT, OUTPUT)} is out of date — run \`npm run build-markers\`.`);
            process.exitCode = 1;
            return;
        }
        console.log(`${path.relative(ROOT, OUTPUT)} is up to date.`);
        return;
    }
    fs.mkdirSync(path.dirname(OUTPUT), {recursive: true});
    fs.writeFileSync(OUTPUT, built);
    const maps = Object.keys(JSON.parse(built).maps);
    console.log(`Wrote ${path.relative(ROOT, OUTPUT)} (${maps.length} maps).`);
}

if (require.main === module) main();

module.exports = {build, SOURCE, OUTPUT, BAKED_INTO_BUNDLED_IMAGES};
