/**
 * Dev-only: build one **map pack** and add it to `packs/index.json`.
 *
 * A map pack is how a new or corrected map reaches users without a ~93 MB app
 * release — the overlay image, the detector templates for that one map, an
 * optional `markers.json` and a `pack.json` manifest, together a few hundred
 * KB. Format and reasoning: `docs/SPEC-MAP-PACKS.md`.
 *
 * ```
 * node scripts/build-pack.js \
 *   --key "deftyconchgaming/Silver Shamrock" \
 *   --image maps-src/silver-shamrock-overlay.png \
 *   --fixture detection-fixtures/tab-silver-shamrock.png \
 *   --fixture detection-fixtures/tab-civilian-silver-shamrock.png \
 *   [--markers markers/silver-shamrock.json] \
 *   [--credit "u/deftyconchgaming"] [--version 2] [--min-app 0.7.0] \
 *   [--out packs] [--base silver-shamrock]
 * ```
 *
 * Nothing here is new logic:
 *
 * - the **templates** come from `scripts/prepare-detector.js`'s own
 *   `buildVariantsForKey` — the same `locatePanel` + `downsample` that builds
 *   the committed `src/core/map-detector/templates.json`, so a pack's
 *   templates are byte-for-byte what the bundled ones would have been;
 * - every **rule** (what a file name may be, what a manifest must hold, what
 *   the index looks like, what counts as a sane PNG) comes from the runtime's
 *   own `src/shared/map-pack-rules.js`, and the finished pack is validated
 *   with it before anything is written. If the app would refuse the pack, this
 *   refuses to publish it.
 *
 * The output is committed to the repository and served by GitHub raw; nothing
 * here uploads anything.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

const rules = require('../src/shared/map-pack-rules');
const {DEFAULT_SIZE} = require('../src/core/map-detector/matcher');
const {buildVariantsForKey, catalog} = require('./prepare-detector');

const ROOT = path.join(__dirname, '..');
const DEFAULT_OUT = path.join(ROOT, 'packs');

/**
 * The keys of the maps that ship inside the app, from the committed `maps/`
 * folder — `prepare-detector.js`'s own catalogue, so there is one answer to
 * "what does this build ship".
 */
function bundledKeys() {
    try {
        return catalog().map(entry => entry.key);
    } catch (err) {
        return [];
    }
}

/** `--key value` / `--flag` into a plain object; `--fixture` may repeat. */
function parseArgs(argv) {
    const args = {fixture: []};
    for (let i = 0; i < argv.length; i++) {
        const token = argv[i];
        if (!token.startsWith('--')) continue;
        const name = token.slice(2);
        const value = (argv[i + 1] && !argv[i + 1].startsWith('--')) ? argv[++i] : true;
        if (name === 'fixture') args.fixture.push(value);
        else args[name] = value;
    }
    return args;
}

function sha256(bytes) {
    return crypto.createHash('sha256').update(bytes).digest('hex');
}

function die(message) {
    console.error(`build-pack: ${message}`);
    process.exit(1);
}

/** Read the index being added to, or an empty valid one. */
function readIndex(file) {
    if (!fs.existsSync(file)) return {formatVersion: rules.PACK_FORMAT, packs: []};
    let json;
    try {
        json = JSON.parse(fs.readFileSync(file, 'utf-8'));
    } catch (err) {
        die(`${path.relative(ROOT, file)} is not valid JSON: ${err.message}`);
    }
    if (!json || typeof json !== 'object' || !Array.isArray(json.packs)) {
        die(`${path.relative(ROOT, file)} has no "packs" array`);
    }
    return json;
}

/**
 * The templates for one map, in exactly the shape the runtime validates:
 * `{format: 2, size, templates: {<key>: [[…size*size numbers…], …]}}`.
 *
 * 3 decimals, like `prepare-detector.js`: 0.001 of a luminance step is far
 * below anything NCC can notice and it keeps a variant at ~24 KB.
 */
async function buildTemplates(key, fixtures) {
    const {variants, parts} = await buildVariantsForKey(fixtures);
    parts.forEach((part, i) => {
        const {loc} = part;
        console.log(`  ${path.basename(part.file).padEnd(40)} ${loc.size}x${loc.size} at ${loc.x},${loc.y}`
            + `  -> variant ${i + 1}/${parts.length}`);
    });
    return {
        format: 2,
        size: DEFAULT_SIZE,
        note: 'Generated by scripts/build-pack.js. Do not edit by hand.',
        templates: {
            [key]: variants.map(thumb => Array.from(thumb, v => Math.round(v * 1000) / 1000))
        }
    };
}

async function main() {
    const args = parseArgs(process.argv.slice(2));

    const key = typeof args.key === 'string' ? args.key : '';
    if (!rules.isValidPackKey(key)) {
        die(`--key "${key}" is not a valid map key. Expected "Creator/Map Name" `
            + `(letters, digits, space, . _ ' ( ) -, and not the reserved "${rules.RESERVED_CREATOR}" creator).`);
    }
    const [keyCreator, keyName] = key.split('/');
    const dirName = rules.packDirName(key);

    if (typeof args.image !== 'string' || !fs.existsSync(args.image)) {
        die('--image <file.png> is required and must exist');
    }
    if (!args.fixture.length) {
        die('at least one --fixture <tab-screenshot.png> is required (the detector template source)');
    }
    for (const fixture of args.fixture) {
        if (!fs.existsSync(fixture)) die(`--fixture ${fixture} does not exist`);
    }

    const outRoot = typeof args.out === 'string' ? path.resolve(args.out) : DEFAULT_OUT;
    const indexFile = path.join(outRoot, 'index.json');
    const index = readIndex(indexFile);

    /*
     * Two ways a key can be *almost* another key, both of which the runtime has
     * to defend against and neither of which should ever be published:
     *
     * 1. Two keys that slug to one install directory. `packDirName` folds every
     *    non-alphanumeric character to `-`, so `a/b c`, `a/b-c`, `a/b.c` and
     *    `a-b/c` all land in `a-b-c`; published together they would reinstall
     *    over each other on every check forever.
     * 2. A key that differs from a **bundled** map's only by case. It would
     *    replace that map (the merges fold case), but the gallery would then
     *    show the pack's spelling — so a pack meant to fix a map would also
     *    rename it. Matching the bundled spelling is always what was meant.
     */
    for (const other of index.packs) {
        if (!other || typeof other.key !== 'string' || other.key === key) continue;
        if (rules.packDirName(other.key) === dirName) {
            die(`--key "${key}" installs into "${dirName}", which "${other.key}" in the index already uses. `
                + 'Two keys that differ only in punctuation share one directory and would overwrite each other.');
        }
    }
    for (const bundled of bundledKeys()) {
        if (bundled !== key && bundled.toLowerCase() === key.toLowerCase()) {
            die(`--key "${key}" differs from the bundled map "${bundled}" only by case. `
                + 'Use the bundled spelling exactly — a pack replaces a bundled map, it does not rename it.');
        }
    }

    // A version is an integer that only ever goes up: the app refuses a
    // downgrade, so re-publishing the same number would be a silent no-op.
    const previous = index.packs.find(p => p && p.key === key);
    const version = args.version !== undefined
        ? parseInt(args.version, 10)
        : ((previous && previous.version ? previous.version : 0) + 1);
    if (!Number.isInteger(version) || version < 1) die('--version must be a positive integer');
    if (previous && version <= previous.version) {
        die(`--version ${version} is not newer than the ${previous.version} already in the index; `
            + 'the app refuses a downgrade, so nothing would install');
    }

    // The display name and creator are **the key's two halves**, never
    // arguments. The app refuses a manifest that spells them differently (a
    // pack calling itself another map's name hijacks every bare-name lookup),
    // so accepting an override here would only ever produce a pack that cannot
    // install. Renaming a map means publishing it under a new key.
    for (const flag of ['name', 'creator']) {
        if (args[flag] !== undefined) {
            die(`--${flag} is not accepted: the ${flag} comes from --key ("${key}"). `
                + 'To change it, publish under a new key.');
        }
    }
    const name = keyName;
    const creator = keyCreator;
    const credit = rules.sanitizeText(args.credit, 200);
    const minApp = typeof args['min-app'] === 'string' ? args['min-app'] : null;
    if (minApp && !/^\d+(\.\d+)*$/.test(minApp)) die('--min-app must look like 1.2.3');

    // The image keeps the map's own name, so the file on disk reads the same
    // way a bundled `maps/<Creator>/<Map Name>.png` does.
    const imageName = `${name}.png`;
    if (!rules.isValidFileName(imageName)) {
        die(`"${imageName}" is not a file name a pack may contain — keep the map name to `
            + 'letters, digits, space, dot, underscore and hyphen');
    }

    const imageBytes = fs.readFileSync(args.image);
    if (!rules.hasPngSignature(imageBytes)) die(`${args.image} is not a PNG`);
    let size = null;
    try {
        size = require('image-size').imageSize(imageBytes);
    } catch (err) {
        die(`${args.image} could not be read by image-size: ${err.message}`);
    }
    if (!rules.isSaneImageSize(size)) {
        die(`${args.image} is ${size && size.width}x${size && size.height}; a map image must be `
            + `${rules.MIN_IMAGE_SIDE}..${rules.MAX_IMAGE_SIDE} px on each side`);
    }
    // The same floor the installer applies: a truncated PNG, or a header with
    // no pixels behind it, would install and leave the map blank.
    if (!rules.isPlausiblePngBytes(imageBytes, size)) {
        die(`${args.image} is ${imageBytes.length} bytes for ${size.width}x${size.height} and/or has no `
            + 'IEND chunk — it looks truncated, and the app would refuse it');
    }

    console.log(`Building ${key} v${version} (${size.width}x${size.height})`);
    const templatesJson = await buildTemplates(key, args.fixture.map(f => path.resolve(f)));
    const templatesBytes = Buffer.from(JSON.stringify(templatesJson, null, 0) + '\n', 'utf-8');
    const templateCheck = rules.validateTemplates(templatesJson, {key, size: DEFAULT_SIZE});
    if (!templateCheck.ok) die(`the generated templates are not valid: ${templateCheck.error}`);

    let markersBytes = null;
    if (typeof args.markers === 'string') {
        if (!fs.existsSync(args.markers)) die(`--markers ${args.markers} does not exist`);
        markersBytes = fs.readFileSync(args.markers);
        if (markersBytes.length > rules.LIMITS.markers) {
            die(`${args.markers} is ${markersBytes.length} bytes; the limit is ${rules.LIMITS.markers}`);
        }
        let markersJson;
        try {
            markersJson = JSON.parse(markersBytes.toString('utf-8'));
        } catch (err) {
            die(`${args.markers} is not valid JSON: ${err.message}`);
        }
        const markerCheck = rules.validateMarkers(markersJson);
        if (!markerCheck.ok) die(`${args.markers} is not a valid markers file: ${markerCheck.error}`);
        console.log(`  markers: ${markerCheck.layers} layer(s), ${markerCheck.points} point(s)`);
    }

    // ── assemble ─────────────────────────────────────────────────────────────
    const files = [
        {name: imageName, bytes: imageBytes},
        {name: rules.TEMPLATES_NAME, bytes: templatesBytes}
    ];
    if (markersBytes) files.push({name: rules.MARKERS_NAME, bytes: markersBytes});

    const listed = files.map(f => ({name: f.name, bytes: f.bytes.length, sha256: sha256(f.bytes)}));
    const total = listed.reduce((sum, f) => sum + f.bytes, 0);
    if (total > rules.LIMITS.pack) {
        die(`the pack is ${total} bytes; the limit is ${rules.LIMITS.pack}`);
    }

    const manifest = {
        formatVersion: rules.PACK_FORMAT,
        key,
        name,
        creator,
        credit,
        version,
        minAppVersion: minApp,
        image: imageName,
        markers: markersBytes ? rules.MARKERS_NAME : null,
        files: listed
    };
    // Validated with the *runtime's* checker before it is written: if the app
    // would refuse this pack, it does not get published.
    const base = typeof args.base === 'string' ? args.base : dirName;
    const entry = {key, version, minAppVersion: minApp, base, files: listed};
    const manifestCheck = rules.validateManifest(manifest, entry, {});
    if (!manifestCheck.ok) die(`the generated manifest is not valid: ${manifestCheck.error}`);

    const packDir = path.join(outRoot, base);
    fs.mkdirSync(packDir, {recursive: true});
    for (const file of files) fs.writeFileSync(path.join(packDir, file.name), file.bytes);
    fs.writeFileSync(path.join(packDir, rules.MANIFEST_NAME), JSON.stringify(manifest, null, 2) + '\n');

    // ── index ────────────────────────────────────────────────────────────────
    index.formatVersion = rules.PACK_FORMAT;
    index.packs = index.packs.filter(p => !p || p.key !== key).concat([entry])
        .sort((a, b) => String(a.key).localeCompare(String(b.key), 'en'));
    const indexCheck = rules.validateIndex(index);
    if (!indexCheck.ok) die(`the updated index is not valid: ${indexCheck.error}`);
    for (const bad of indexCheck.rejected) {
        die(`the updated index holds an entry the app would reject: ${bad.key || '(unnamed)'} (${bad.reason})`);
    }
    fs.writeFileSync(indexFile, JSON.stringify(index, null, 2) + '\n');

    const relative = path.relative(ROOT, packDir);
    console.log(`\nWrote ${relative}/ (${listed.length + 1} files, ${(total / 1024).toFixed(1)} KB)`);
    for (const file of listed) console.log(`  ${file.name.padEnd(28)} ${String(file.bytes).padStart(8)}  ${file.sha256}`);
    console.log(`Updated ${path.relative(ROOT, indexFile)} (${index.packs.length} pack(s))`);
    console.log('\nCommit and push these; the app reads them from GitHub raw on its next check.');
}

module.exports = {parseArgs, sha256, buildTemplates, readIndex};

if (require.main === module) {
    main().catch(err => {
        console.error(err);
        process.exit(1);
    });
}
