'use strict';

/**
 * Build `hmo-updater.exe` — the themed updater window — out of `updater/*.cs`.
 *
 * No msbuild, no NuGet, no Visual Studio: the only compiler involved is the
 * `csc.exe` that ships inside Windows itself, and the only assemblies
 * referenced are the WPF ones that ship with the .NET Framework 4.x every
 * Windows 10/11 already has. That is the whole point — the helper must not add
 * a toolchain to a project whose build today is `npm ci && electron-builder`,
 * and it must not add a runtime the user has to install.
 *
 * Output (git-ignored) is `build/updater/`, which package.json ships through
 * `extraResources` to `resources/updater/`:
 *
 *   build/updater/hmo-updater.exe
 *   build/updater/fonts/*.ttf + OFL.txt
 *   build/updater/icon.png
 *
 * Two files are generated rather than written by hand:
 *
 * - `Strings.g.cs` from `updater/strings.json`, with every non-ASCII character
 *   escaped as `\uXXXX`. csc's default source encoding depends on the machine's
 *   ANSI codepage, so an `è` written straight into a .cs file is a coin toss on
 *   a CI runner; an escape is not. This also means the helper reads no file at
 *   runtime, so a missing or corrupt strings.json can never strand a user in
 *   front of a half-drawn window mid-update.
 * - `AssemblyInfo.g.cs`, so the exe carries the product name and the app's
 *   version in its file properties instead of 0.0.0.0.
 *
 * Run it with `npm run build-updater`; `npm run build` / `build:win` run it
 * first, and `.github/workflows/release.yml` has its own step.
 */

const fs = require('fs');
const path = require('path');
const {spawnSync} = require('child_process');

const root = path.join(__dirname, '..');
const sourceDir = path.join(root, 'updater');
const outDir = path.join(root, 'build', 'updater');
/** Generated sources. Not shipped, not committed; `build/.updater-obj`. */
const objDir = path.join(root, 'build', '.updater-obj');

/** The WPF assemblies, relative to the framework directory. */
const REFERENCES = [
    'WPF\\PresentationCore.dll',
    'WPF\\PresentationFramework.dll',
    'WPF\\WindowsBase.dll',
    'System.Xaml.dll',
    'System.dll',
    'System.Core.dll'
];

/**
 * The .NET Framework 4 directory that holds csc.exe and the WPF assemblies.
 *
 * 64-bit first: the helper is `anycpu`, but the *reference* assemblies have to
 * come from somewhere and the 64-bit tree is the one that exists on every
 * supported machine. The 32-bit fallback is for a hypothetical x86 runner.
 */
function frameworkDir() {
    const windir = process.env.WINDIR || 'C:\\Windows';
    const candidates = [
        path.join(windir, 'Microsoft.NET', 'Framework64', 'v4.0.30319'),
        path.join(windir, 'Microsoft.NET', 'Framework', 'v4.0.30319')
    ];
    for (const dir of candidates) {
        if (fs.existsSync(path.join(dir, 'csc.exe'))) return dir;
    }
    return null;
}

/** `"è"` → `"\u00e8"`. Everything printable ASCII is left alone. */
function csharpLiteral(value) {
    let out = '"';
    for (const ch of String(value)) {
        const code = ch.codePointAt(0);
        if (ch === '"') out += '\\"';
        else if (ch === '\\') out += '\\\\';
        else if (ch === '\n') out += '\\n';
        else if (ch === '\r') out += '\\r';
        else if (code < 0x20 || code > 0x7e) {
            // Surrogate pairs come out as two escapes, which is what a C#
            // string holds anyway.
            for (let i = 0; i < ch.length; i++) {
                out += '\\u' + ch.charCodeAt(i).toString(16).padStart(4, '0');
            }
        } else out += ch;
    }
    return out + '"';
}

function generateStrings(strings) {
    const lines = [];
    // ASCII only, comments included: the whole point of the escaping below is
    // that csc never has to guess this file's encoding.
    lines.push('// GENERATED by scripts/build-updater.js from updater/strings.json - do not edit.');
    lines.push('using System.Collections.Generic;');
    lines.push('');
    lines.push('namespace HmoUpdater');
    lines.push('{');
    lines.push('    internal static partial class Strings');
    lines.push('    {');
    lines.push('        private static void Fill(Dictionary<string, string> en, Dictionary<string, string> it)');
    lines.push('        {');
    for (const [lang, variable] of [['en', 'en'], ['it', 'it']]) {
        for (const key of Object.keys(strings[lang])) {
            lines.push(`            ${variable}[${csharpLiteral(key)}] = ${csharpLiteral(strings[lang][key])};`);
        }
        lines.push('');
    }
    lines.push('        }');
    lines.push('    }');
    lines.push('}');
    return lines.join('\r\n') + '\r\n';
}

function generateAssemblyInfo(pkg) {
    const version = /^\d+\.\d+\.\d+$/.test(pkg.version) ? pkg.version + '.0' : '0.0.0.0';
    const product = (pkg.build && pkg.build.productName) || pkg.name;
    return [
        '// GENERATED by scripts/build-updater.js - do not edit.',
        'using System.Reflection;',
        'using System.Runtime.Versioning;',
        '',
        // Without a TargetFramework attribute the CLR applies the *oldest*
        // quirks it knows, and WPF then ignores the manifest's per-monitor DPI
        // declaration. csc alone never emits one; msbuild does.
        '[assembly: TargetFramework(".NETFramework,Version=v4.0", FrameworkDisplayName = ".NET Framework 4")]',
        `[assembly: AssemblyTitle(${csharpLiteral(product + ' Updater')})]`,
        `[assembly: AssemblyProduct(${csharpLiteral(product)})]`,
        `[assembly: AssemblyDescription(${csharpLiteral('Installs an update to ' + product + '.')})]`,
        `[assembly: AssemblyCompany(${csharpLiteral(pkg.author || '')})]`,
        `[assembly: AssemblyCopyright(${csharpLiteral('Apache-2.0')})]`,
        `[assembly: AssemblyVersion(${csharpLiteral(version)})]`,
        `[assembly: AssemblyFileVersion(${csharpLiteral(version)})]`,
        ''
    ].join('\r\n');
}

function copyInto(from, to) {
    fs.mkdirSync(path.dirname(to), {recursive: true});
    fs.copyFileSync(from, to);
}

function main() {
    const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf-8'));
    const framework = frameworkDir();
    if (!framework) {
        // Loud, with the reason: on a runner this is the difference between a
        // release that ships the helper and a release that silently does not.
        console.error('build-updater: no csc.exe found under %WINDIR%\\Microsoft.NET\\Framework64\\v4.0.30319.');
        console.error('The .NET Framework 4.x compiler is part of Windows; this build cannot produce hmo-updater.exe without it.');
        process.exit(1);
    }

    const strings = JSON.parse(fs.readFileSync(path.join(sourceDir, 'strings.json'), 'utf-8'));
    fs.rmSync(objDir, {recursive: true, force: true});
    fs.mkdirSync(objDir, {recursive: true});
    fs.writeFileSync(path.join(objDir, 'Strings.g.cs'), generateStrings(strings), 'utf-8');
    fs.writeFileSync(path.join(objDir, 'AssemblyInfo.g.cs'), generateAssemblyInfo(pkg), 'utf-8');

    const sources = fs.readdirSync(sourceDir)
        .filter(name => name.endsWith('.cs'))
        .map(name => path.join(sourceDir, name))
        .concat([path.join(objDir, 'Strings.g.cs'), path.join(objDir, 'AssemblyInfo.g.cs')]);

    fs.mkdirSync(outDir, {recursive: true});
    const exe = path.join(outDir, 'hmo-updater.exe');
    const args = [
        '/nologo',
        '/target:winexe',
        '/platform:anycpu',
        '/optimize+',
        '/utf8output',
        '/warn:4',
        `/out:${exe}`,
        `/win32manifest:${path.join(sourceDir, 'app.manifest')}`,
        `/win32icon:${path.join(root, 'build', 'icon.ico')}`
    ];
    for (const reference of REFERENCES) args.push(`/r:${path.join(framework, reference)}`);
    args.push(...sources);

    const result = spawnSync(path.join(framework, 'csc.exe'), args, {stdio: 'inherit'});
    if (result.error) {
        console.error('build-updater: could not run csc.exe:', result.error.message);
        process.exit(1);
    }
    if (result.status !== 0) {
        console.error(`build-updater: csc.exe exited with ${result.status}.`);
        process.exit(result.status || 1);
    }

    // Fonts: the static TTFs WPF can actually load, straight from the repo.
    const fontsFrom = path.join(sourceDir, 'fonts');
    const fontsTo = path.join(outDir, 'fonts');
    fs.rmSync(fontsTo, {recursive: true, force: true});
    for (const name of fs.readdirSync(fontsFrom)) copyInto(path.join(fontsFrom, name), path.join(fontsTo, name));

    // The same icon the app's loading overlay shows, so the two screens carry
    // literally the same picture.
    copyInto(path.join(root, 'src', 'images', 'icon.png'), path.join(outDir, 'icon.png'));

    const bytes = fs.statSync(exe).size;
    console.log(`build-updater: ${path.relative(root, exe)} (${bytes} bytes), ` +
        `${fs.readdirSync(fontsTo).length} font files, icon.png`);
}

if (require.main === module) main();

// Exported for `test/updater-strings.test.js`: the escaping is the one piece of
// this script that can be wrong in a way nobody sees until an Italian string
// comes out as mojibake on a CI-built release.
module.exports = {csharpLiteral, generateStrings, frameworkDir};
